local/cart/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    path('order/', views.order, name = 'order')
]

local/catalog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'catalog'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^books/$', views.book_list, name='books'),
    path('books/<category_slug>/',views.book_list,name='books-by-genre'),
    path('edit/',views.edit, name='edit'),
    path('book/<id>/  ', views.product_detail, name='book-detail'),
    re_path(r'^login/$', views.user_login, name='login'),
    re_path(r'^register/$', views.register, name='register'),
    path('profile/<str:username>/',views.profilePage,name='profile'),
    path('search/', views.searchresult, name='search_result'),
    path('logout/', views.custom_logout, name='logout'),
    path('contacts/', views.contacts, name='contacts')
    
    
    
]
# /?page=4 ? -> GET

local/local/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('catalog/', include('catalog.urls',namespace='catalog')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

local/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from catalog.models import Book
import datetime

# Create your models here.
class Cart(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    book_id = models.ForeignKey(Book, on_delete=models.CASCADE) 
    count = models.IntegerField()
    total_price = models.FloatField()
    
class Order(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE,null=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    city = models.CharField(max_length=300)
    datetime = models.DateField(default=datetime.datetime.now().strftime("%Y-%m-%d"))
    

local/cart/forms.py
from django import forms
from .models import Order

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','city',]
    

local/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from catalog.models import Book
from cart.models import Cart
from cart.models import Order
from django.contrib.auth.decorators import login_required
import datetime
from .forms import CartAddProductForm, OrderForm
# Create your views here.


@login_required(login_url='catalog:login')
def cart_detail(request):
    cart = Cart.objects.filter(user_id = request.user)
    sum = 0
    for item in cart:
        sum += item.total_price
    if request.method == "POST":
        id_dd = request.POST.get("product")
        item = Cart.objects.filter(id = id_dd)
        item.delete()
        return render(request, 'cart/detail.html', {'cart': cart, 'summary':sum})
    else:
        return render(request, 'cart/detail.html', {'cart': cart, 'summary':sum})
    
@login_required(login_url='catalog:login')
def order(request):
    cart = Cart.objects.filter(user_id = request.user)
    sum = 0
    form =  OrderForm(request.POST)
    for item in cart:
        sum += item.total_price
    if request.method == 'POST':
        if form.is_valid:
            form.save()
            for item in cart:
                item.book_id.order_count += item.count
                item.book_id.save()
                item.delete()
            return redirect(to='/catalog/')
    else:
        return render(request, 'cart/order.html', {'cart': cart, 'summary':sum, 'form': form})

local/cart/templates/cart/detail.html
{% extends "base_generic.html" %}
{% block content %}
<div class="d-flex flex-column">
    
    <h1>Your shopping cart</h1>
    <table class="cart text-center">
        <thead>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
    {% if cart %}
        {% for item in cart %}
            {% with product=item.book_id %}
            
                <tr class="text-center">
                    <td class="d-flex mx-3">{{ product.name }}</td>
                    <td>{{ item.count }}</td>
                    <td class="num  mx-3">${{ product.price }}</td>
                    <td class="num  mx-3">${{ item.total_price }}</td>
                    <td>
                        <form method="POST">
                            {% csrf_token %}
                            <button type="submit" name="product" value="{{item.id}}">Remove</button>
                        </form>
                    </td>
                </tr>
                
                
            {% endwith %}
        {% endfor %}
        <tr class="total my-3">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ summary }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right my-4 mx-4">
        <a href="{% url "catalog:books" %}" class="button light">Continue shopping</a>
        <a href="{% url "cart:order" %}" class="button mx-5">Checkout</a>
    </p>
    {% else %}
        <section class="empty-cart page-wrapper">
    <div class="container">
        <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="block text-center">
                <i class="tf-ion-ios-cart-outline"></i>
                <h1 class="text-center">Ваша корзина пуста.</h1>
            
                <a href="{% url 'catalog:books' %}" class="btn btn-main mt-20">За покупками!</a>
        </div>
        </div>
    </div>
    </section>
</div>
        {% endif %}
{% endblock %}

local/cart/templates/cart/order.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="d-flex flex-column">
    {%if cart %}
        <h1 style="margin-bottom:30px">Go on and order this</h1>
        <table class="cart text-center">
            <thead>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Unit price</th>
                <th>Price</th>
            </tr>
            </thead>
            <tbody>
        {% for item in cart%}
            {% with product=item.book_id %}
                
            <tr class="text-center">
                <td class="d-flex mx-3">{{ product.name }}</td>
                <td>{{ item.count }}</td>
                <td class="num  mx-3">${{ product.price }}</td>
                <td class="num  mx-3">${{ item.total_price }}</td>
            </tr> 
            {% endwith %}
        {% endfor %}
            <tr class="total my-3">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">${{ summary }}</td>
            </tr>
            </tbody>
        </table>
        <p>Fulfill the fields down there</p>
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-dark my-2">Подтвердить изменение профиля</button>
        </form>
    {% else %}
    {% endif %}
</div>
{% endblock %}