local/cart/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    path('order/', views.order, name = 'order')
]

local/catalog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'catalog'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^books/$', views.book_list, name='books'),
    path('books/<category_slug>/',views.book_list,name='books-by-genre'),
    path('edit/',views.edit, name='edit'),
    path('book/<id>/  ', views.product_detail, name='book-detail'),
    re_path(r'^login/$', views.user_login, name='login'),
    re_path(r'^register/$', views.register, name='register'),
    path('profile/<str:username>/',views.profilePage,name='profile'),
    path('search/', views.searchresult, name='search_result'),
    path('logout/', views.custom_logout, name='logout'),
    path('contacts/', views.contacts, name='contacts')
    
    
    
]
# /?page=4 ? -> GET

local/local/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('catalog/', include('catalog.urls',namespace='catalog')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

local/catalog/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User


# Create your models here.



class Language(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
         return self.name


class Author(models.Model):

     first_name = models.CharField(max_length=100, help_text="Enter author first name")
     last_name = models.CharField(max_length=100, help_text="Enter author lastname")

     def __str__(self):
         return f'{self.first_name} {self.last_name}'

     def get_absolute_url(self):
         return reverse('author-detail', args=[str(self.id)])



class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('catalog:books-by-genre',
                        args=[self.slug])

    

class Book(models.Model):
    author = models.ForeignKey(Author,null=True,on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='products',on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True,default="Book")
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=20)
    available = models.BooleanField(default=True)
    click_count = models.IntegerField(default=0)
    order_count = models.IntegerField(default=0)
    
    
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
   
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:book-detail', args=[str(self.id)])





#PascalCase C# camel_case python


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    bio=models.TextField(null=True, blank=True)
    
    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

local/catalog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']
    
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio',)

local/catalog/views.py
from .models import *
from .forms import *
from django.views import generic
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from cart.forms import CartAddProductForm
from django.shortcuts import render, get_object_or_404, redirect
from cart.models import Cart
from django.db.models import Q
from django.contrib.auth.decorators import login_required

@login_required(login_url='login/')
def index(request):
    book_count = Book.objects.all().count() #count(select * from Book)
    author_count = Author.objects.all().count()
    return render(
        request,
        'index.html',
        context={'book_count': book_count, 'author_count': author_count}
    )

@login_required(login_url='login/')
def book_list(request, category_slug=None):
    paginate_by = 4
    category = None
    categories = Category.objects.all()
    products = Book.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'catalog/book_list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})

    


@login_required(login_url='login/')
def contacts(request):
    return render(request, 'catalog/contacts.html')


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(to='/catalog/profile/{}'.format(user.get_username()))
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})

@login_required(login_url='login/')
def custom_logout(request):
    logout(request)
    return redirect(to='/catalog/login/')

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            profile = Profile.objects.create(user=new_user)
            return render(request, 'registration/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'user_form': user_form})

@login_required(login_url='login/')
def profilePage(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    return render(request, 'catalog/profile.html', {'profile': profile, 'user':user})
    
@login_required(login_url='login/')
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect(to='/catalog/profile/{}'.format(request.user.get_username()))
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
        return render(request,
                      'catalog/edit.html',
                      {'user_form': user_form,
                       'profile_form': profile_form})

@login_required(login_url='login/')
def product_detail(request,id):
    product = get_object_or_404(Book,
                                    id=id)
    cart_product_form = CartAddProductForm()
    product.click_count += 1
    product.save()
    if product.stock == 0:
        product.available = False
        product.save()
    if request.method == 'POST':
        user_id = request.user
        count = request.POST.get("count")
        price = request.POST.get("price")
        if(product.stock >= int(count)):
            product.stock -= int(count)
            product.save()
        else:
            count = product.stock
        Cart.objects.create(user_id=user_id,book_id=product,count=count, total_price=int(count)*float(price))
        
        return render(request, 'catalog/book_detail.html', {'book': product,
                                                            'cart_product_form': cart_product_form})
    else:
        
        return render(request, 'catalog/book_detail.html', {'book': product,
                                                            'cart_product_form': cart_product_form})

@login_required(login_url='login/')  
def searchresult(request):
    query = request.GET.get('q')
    print(query)
    object_list = Book.objects.filter(Q(name__icontains=query) | Q(slug__icontains=query) | Q(category__name__icontains=query))
    return render(request, 'catalog/search_result.html', {'object_list':object_list})

local/catalog/templates/catalog/book_detail.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="d-flex flex-column">
    <h1 style="margin-bottom:30px">Title: {{book.name}}</h1>

    <p><b>Author: </b>{{book.author}}</p>
    <p><b>Summary: </b>{{book.description}}</p>
    <p><b>Genres: </b>{{book.category}}</p>
    <p><b>Price: </b>{{book.price}}rubles</p>
    {%if book.available%}
    <p><b>Available</b> {{book.stock}}</p>
    <form action="{% url "catalog:book-detail" book.id %}" method="post" class="d-flex flex-column text-center">
        {% csrf_token %}
        <p>Введите количество книг для добавления в корзину</p>
        <input type="number" name="count"/>
        <input type="submit" value="Add to cart">
        <input style = "display: none;" name="user_id" value="{{ user }}"/>
        <input style = "display: none;" name="price" value="{{ book.price }}"/>
        
    </form>
    <p><b>Visitors count</b>: {{book.click_count}}</p>
    <p><b>Order count</b>: {{book.order_count}}</p>
    {% else %}
    <p><b>Not Available</b></p>
    {%endif%}
</div>
{% endblock %}

local/catalog/templates/catalog/book_list.html
{% extends 'base_generic.html' %}


{% block content %}
    <div id="sidebar" class="nav nav-pills flex-column mb-auto" style="width: fit-content;">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %} class="selected"{% endif %}>
                <a href="{% url "catalog:books" %}">All</a>
            </li>
            {% for c in categories %}   
                <li {% if category.slug == c.slug %} class="selected" {% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="d-flex flex-column mx-4">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        <div class="d-flex my-5">
            {% for product in products %}
            <br/>
                <div class="item  d-flex flex-column text-center mx-3 align-items-center" style="width: 150px;height: 150px;">
                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                    ${{ product.price }}
                </div>
            {% endfor %}
        </div>
    </div>
    
{% endblock %}

local/catalog/templates/catalog/contacts.html
{% extends 'base_generic.html' %}


{% block content %}
   <p>Впишите сюда свои контакты</p>
    
{% endblock %}

local/catalog/templates/catalog/edit.html
{% extends 'base_generic.html' %}
{% block content %}
<div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
       <div class="card-title nth-card-title">
          <h4>Изменение профиля</h4>
       </div>
       <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p}}
          {{ form.as_p }}
          <div class="d-grid gap-2 d-md-block mt-2">
             <button type="submit" class="btn btn-dark">Подтвердить изменение профиля</button>
          </div>
       </form>
    </div>
 </div>
{% endblock %}

local/catalog/templates/catalog/profile.html
{% extends 'base_generic.html' %}


{% block content %}
    <div class="d-flex flex-column align-items-center">   
        <h1>Your profile</h1>
        <p>You can edit it. to do so, you can press "edit" button</p>
        
        <form action="." method="post" enctype="multipart/form-data" class="d-flex flex-column text-center">
            Nickname:{{profile.user.username}}
            <br/>
            Firstname: {{user.first_name}}
            <br/>
            Lastname: {{user.last_name}}
            <br/>
            Email: {{user.email}}
            <br/>
            Info: {{ profile.bio }}
            {% csrf_token %}
            <br/>
            <a href="{% url 'catalog:edit' %}" class="btn btn-dark">Edit</a>
        </form>
    </div> 
{% endblock %}

local/catalog/templates/catalog/search_result.html
{% extends "base_generic.html"%}

{% block content %}
  <h1>Search Results</h1>
  
  <ul style="list-style-type: none;">
    {% for book in object_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.name }}</p>
      </li>
    {% endfor %}
  </ul>
{% endblock %}