local/cart/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    path('order/', views.order, name = 'order')
]

local/catalog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'catalog'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^books/$', views.book_list, name='books'),
    path('books/<category_slug>/',views.book_list,name='books-by-genre'),
    path('edit/',views.edit, name='edit'),
    path('book/<id>/  ', views.product_detail, name='book-detail'),
    re_path(r'^login/$', views.user_login, name='login'),
    re_path(r'^register/$', views.register, name='register'),
    path('profile/<str:username>/',views.profilePage,name='profile'),
    path('search/', views.searchresult, name='search_result'),
    path('logout/', views.custom_logout, name='logout'),
    path('contacts/', views.contacts, name='contacts')
    
    
    
]
# /?page=4 ? -> GET

local/local/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('catalog/', include('catalog.urls',namespace='catalog')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

local/catalog/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User


# Create your models here.



class Language(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
         return self.name


class Author(models.Model):

     first_name = models.CharField(max_length=100, help_text="Enter author first name")
     last_name = models.CharField(max_length=100, help_text="Enter author lastname")

     def __str__(self):
         return f'{self.first_name} {self.last_name}'

     def get_absolute_url(self):
         return reverse('author-detail', args=[str(self.id)])



class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('catalog:books-by-genre',
                        args=[self.slug])

    

class Book(models.Model):
    author = models.ForeignKey(Author,null=True,on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='products',on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True,default="Book")
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=20)
    available = models.BooleanField(default=True)
    click_count = models.IntegerField(default=0)
    order_count = models.IntegerField(default=0)
    
    
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
   
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:book-detail', args=[str(self.id)])





#PascalCase C# camel_case python


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    bio=models.TextField(null=True, blank=True)
    
    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

local/catalog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']
    
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio',)

local/catalog/views.py
from .models import *
from .forms import *
from django.views import generic
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from cart.forms import CartAddProductForm
from django.shortcuts import render, get_object_or_404, redirect
from cart.models import Cart
from django.db.models import Q
from django.contrib.auth.decorators import login_required

@login_required(login_url='login/')
def index(request):
    book_count = Book.objects.all().count() #count(select * from Book)
    author_count = Author.objects.all().count()
    return render(
        request,
        'index.html',
        context={'book_count': book_count, 'author_count': author_count}
    )

@login_required(login_url='login/')
def book_list(request, category_slug=None):
    paginate_by = 4
    category = None
    categories = Category.objects.all()
    products = Book.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'catalog/book_list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})

    


@login_required(login_url='login/')
def contacts(request):
    return render(request, 'catalog/contacts.html')


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(to='/catalog/profile/{}'.format(user.get_username()))
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})

@login_required(login_url='login/')
def custom_logout(request):
    logout(request)
    return redirect(to='/catalog/login/')

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            profile = Profile.objects.create(user=new_user)
            return render(request, 'registration/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'user_form': user_form})

@login_required(login_url='login/')
def profilePage(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    return render(request, 'catalog/profile.html', {'profile': profile, 'user':user})
    
@login_required(login_url='login/')
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect(to='/catalog/profile/{}'.format(request.user.get_username()))
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
        return render(request,
                      'catalog/edit.html',
                      {'user_form': user_form,
                       'profile_form': profile_form})

@login_required(login_url='login/')
def product_detail(request,id):
    product = get_object_or_404(Book,
                                    id=id)
    cart_product_form = CartAddProductForm()
    product.click_count += 1
    product.save()
    if product.stock == 0:
        product.available = False
        product.save()
    if request.method == 'POST':
        user_id = request.user
        count = request.POST.get("count")
        price = request.POST.get("price")
        if(product.stock >= int(count)):
            product.stock -= int(count)
            product.save()
        else:
            count = product.stock
        Cart.objects.create(user_id=user_id,book_id=product,count=count, total_price=int(count)*float(price))
        
        return render(request, 'catalog/book_detail.html', {'book': product,
                                                            'cart_product_form': cart_product_form})
    else:
        
        return render(request, 'catalog/book_detail.html', {'book': product,
                                                            'cart_product_form': cart_product_form})

@login_required(login_url='login/')  
def searchresult(request):
    query = request.GET.get('q')
    print(query)
    object_list = Book.objects.filter(Q(name__icontains=query) | Q(slug__icontains=query) | Q(category__name__icontains=query))
    return render(request, 'catalog/search_result.html', {'object_list':object_list})

local/catalog/templates/base_generic.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}<title>Local Library</title>{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    {% load static %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="h-100">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        {% block header %}
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class = 'navbar-item nav-link mx-2' href="{% url 'catalog:index'%}">Home</a>
                
                <a class = 'navbar-item nav-link mx-2' href="{% url 'catalog:books' %}">All Books</a>
                
                <a class = 'navbar-item nav-link mx-2' href="{% url 'catalog:profile' username=request.user.username%}">{{user.username}}</a>
                
                <form action = "{% url 'catalog:search_result' %}"  class="d-flex align-items-center">
                    <input name="q" type="text" placeholder="Search...">
                </form>
                <a class = 'navbar-item nav-link' href = "{% url 'cart:cart_detail'%}" style="margin-left: 20px;">Cart</a>
                <a class = 'navbar-item nav-link' href = "{% url 'catalog:logout' %}">Logout</a>
                <a class = 'navbar-item nav-link' href="{% url 'catalog:contacts' %}">Contacts</a>
                {%endif%}
                
            </div>
        {% endblock %}
    </nav>
    <div class="container h-100 mt-5 d-flex">
                {% block content %}{% endblock %}
                {% block pagination %}
                {%if is_paginated%}
                <div class = "pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous%}
                        <a href="{{request.path}}?page={{page_obj.previous_page_number}}">Prev</a>
                        {%endif%}
                        <span>
                              &nbsp; Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}&nbsp;
                        </span>
                        {% if page_obj.has_next%}
                        <a href="{{request.path}}?page={{page_obj.next_page_number}}">Next</a>
                        {%endif%}
                    </span>
                </div>
                {%endif%}


                {% endblock %}
            </div>

</body>
</html>

local/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
    <div class=" bg-dark h-100 align-items-center d-flex flex-column mx-auto" style="width: fit-content;">
        <p class="text-white my-3 mx-3"> Добро пожловать в магазин книг.</p>
        
        <a class="text-white bg-none my-3 mx-3" href="{% url 'catalog:books' %}">Перейти в каталог</a>
    </div>

{% endblock %}